### ISSUE TITLE
I would like to know about the operating environment of code-samples(Python)

### ISSUE THREAD

**Issue by Massas** [tiyaro/code-samples#3]
I would like to know about the operating environment of code-samples(Python).
I would like to run python\stable-diffusion\stableDiffusionDemo.py

I opened cmd on the VSCode terminal and followed the instructions in README.md.

-----

(1) pip install -r requirements.txt
All items are now displayed as "Requirement already satisfied"

(2) SET TIYARO_API_KEY="MY_API_KEY"
If you want to set APIKey as an environment variable when executing with Windows cmd, this command is correct, not the export command, is it correct?

(3) python . /stableDiffusionDemo.py
The code in stableDiffusionDemo.py was not changed from the cloned state, and when the sample was executed, an error occurred.
The error is as follows

```
C:\OSS\code-samples\python\stable-diffusion>python . /stableDiffusionDemo.py
Traceback (most recent call last):
  File "C:\OSS\code-samples\python\stable-diffusion\stableDiffusionDemo.py", line 45, in <module
    resp = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
-----
Is it possible to run the sample in my operating environment?
cmd on VSCode

If it is possible, I would like you to add a note to README.md about the operating environment, such as the operating system on which the sample is supposed to run.

Thank you for your cooperation.

**Comment by Venkat2811** [comment]
Hello @Massas ,

Thanks for reaching out. 

> (2) SET TIYARO_API_KEY="MY_API_KEY"
yes, for windows this is the correct command.  (I cross checked it here https://superuser.com/a/79614).

From your error logs, the program was able to run but received Error response from Stable Diffusion API, there is no issue with your OS setup.  We also didn't add OS details to README because these are basic python scripts and we expect it to run on all standard OS.

Could you add the following print statement below line number 45 and share error response you see:
```
print(response.text)
```

Kindly note that stable diffusion is not available on free plan. (Just mentioning this as this a common error that we see).

**Comment by Massas** [comment]
Hello @Venkat2811 ,

Thank you for your reply!

>(2) SET TIYARO_API_KEY="MY_API_KEY"
yes, for windows this is the correct command.(I cross checked it here https://superuser.com/a/79614).

Thank you. I understand.

>From your error logs, the program was able to run but received Error response from Stable Diffusion API, there is no issue with your OS setup. add OS details to README because these are basic python scripts and we expect it to run on all standard OS.

I also understand this. Thank you.
It is good to know that there is no problem with the OS configuration.

>Could you add the following print statement below line number 45 and share error response you see:
print(response.text)

I added the sentence you gave me and tried again.
The result was as follows I will share it with you.
```
Auth required
```

My APIKey has a status of "Active", but maybe I didn't generate an APIKey for StableDiffusion.
How about this?

<img width="1103" alt="APIKey-is-Active" src="https://user-images.githubusercontent.com/12912140/206885362-cfa20042-194e-4087-bde8-1002139cac7c.png">

**Comment by Venkat2811** [comment]
> Auth required
This error means, your API key is not set correctly.

I hope you copied the API-KEY that was displayed when you created it.  The one hidden red in the above screenshot is just id of the API key.

Could you try printing and very that your API key is set correctly ?

Also, one correction from earlier - 

> Kindly note that stable diffusion is not available on free plan. (Just mentioning this as this a common error that we see).

This is incorrect. My apologies.

I would also recommend using the latest SD model:
```
https://api.tiyaro.ai/v1/ent/huggingface/1/stabilityai/stable-diffusion-2-1?serviceTier=gpuflex
```

**Comment by Massas** [comment]
>Could you try printing and very that your API key is set correctly ?

I made a mistake. Thanks for letting me know.

I set the environment variables without single or double quotes in the SET command, I was able to run it with the old model.
I made a mistake too!

```
SET TIYARO_API_KEY=API-Key
```

It seems that the SET command was designed to set the value given as the right operand as it is as an environment variable, regardless of the data type. I didn't know it.
I had a preconceived notion that APIKey is treated as "string data" like "API-KEY" or 'API-KEY', 
and I was trying to give the value to the SET command as string data by adding quotation marks.
So, API had extra data(quotation('/")) in it, and it turned out to be ”Auth reuired".
So, it turns out that the way the environment variable was set was the cause of this whole event. 

>I would also recommend using the latest SD model:

I also tried the latest model you mentioned, but this one was not available on my free plan.
```
{"statusCode": 400, "error": "Top Level Exception converted to string: Model is not available in the free plan"}
```

It would be great to be able to use StableDiffusion via the API.
Thank you very much for having this conversation!

**Comment by Massas** [comment]
@Venkat2811 
Of course! With pleasure.
I will try it after work today, so please wait a while.

**Comment by Venkat2811** [comment]
Thanks for confirming @Massas .  I'm glad you are able to use Stable diffusion 2.1 APIs without any issue !

I'll close this issue now.  Please feel free to create new issue or reach out to us at help@tiyaro.ai if you have any other questions
